#!/bin/sh

# for nvm symlink (sh)
# sudo ln -s "$(which node)" /usr/local/bin/node

cd "$(git rev-parse --show-toplevel)"
VUECLI="npx vue-cli-service"
pwd

STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep -e ".js$" -e ".vue$"))

echo "${STAGED_FILES[@]}"

echo "ESLint checking in ${#STAGED_FILES[@]} files"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

$VUECLI lint "${STAGED_FILES[@]}"

VUECLI_EXIT="$?"

git add "${STAGED_FILES[@]}"

if [[ "${VUECLI_EXIT}" == 0 ]]; then
  printf "COMMIT SUCCEEDED"
else
  printf "COMMIT FAILED"
  exit 1
fi

exit $?
