name: GocAdminVue Package

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@gocteam'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Retrieve version from package.json
        if: ${{ success() }} || ${{ failure() }}
        run: |
          echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      # - name: Notify dedicated teams channel [SUCCESS]
      #   if: ${{ success() }}
      #   uses: jdcargile/ms-teams-notification@v1.3
      #   with:
      #     github-token: ${{ github.token }} # this will use the runner's token.
      #     ms-teams-webhook-uri: ${{ secrets.GAMEFLEX_SOFTWARE_GENERAL_MS_TEAMS_WEBHOOK_URI }}
      #     notification-summary: Goc Admin Vue [${{ env.PACKAGE_VERSION }}] PROD Deployed
      #     notification-color: 17a2b8
      #     timezone: Europa/Istanbul
      # - name: Notify dedicated teams channel [FAILED]
      #   if: ${{ failure() }}
      #   uses: jdcargile/ms-teams-notification@v1.3
      #   with:
      #     github-token: ${{ github.token }} # this will use the runner's token.
      #     ms-teams-webhook-uri: ${{ secrets.GAMEFLEX_SOFTWARE_GENERAL_MS_TEAMS_WEBHOOK_URI }}
      #     notification-summary: Goc Admin Vue [${{ env.PACKAGE_VERSION }}] PROD FAILED!!! 
      #     notification-color: b4280a
      #     timezone: Europa/Istanbul
